defaults:
  - /highlight_parser@highlight_parser: readwise_markdown
  - /encoder@encoder: sentence_transformer
  - /extractor@extractor: local_llm
  - /clusterer@clusterer: hdbscan
  - _self_

device: cpu
