# Make a copy of this file, rename it to secrets.yaml, and fill in the values with your API keys. Do not commit secrets.yaml to git, as it is included in .gitignore.
secrets:
  claude_api: ???
  readwise_api: ???